#!/bin/bash

# Sanity Studio - Development Server Startup Guide
# Run this script or follow the commands below to start the studio locally

# ============================================================================
# QUICK START - RUN THESE COMMANDS
# ============================================================================

echo "Starting Sanity Studio Development Server..."
echo ""
echo "Step 1: Navigate to studio directory"
echo "$ cd studio-project-bottleneck"
echo ""
echo "Step 2: Install dependencies (if not already done)"
echo "$ npm install"
echo ""
echo "Step 3: Start development server"
echo "$ npm run dev"
echo ""
echo "The studio will be available at: http://localhost:3333"
echo ""
echo "============================================================================"
echo "WHAT HAPPENS WHEN YOU RUN 'npm run dev'"
echo "============================================================================"
echo ""
echo "1. Sanity CLI initializes the development server"
echo "2. Connects to Sanity project 'vtm50qra', dataset 'production'"
echo "3. Loads schemas: Post, Product, Author"
echo "4. Starts local development server on port 3333"
echo "5. Opens browser to http://localhost:3333"
echo ""
echo "============================================================================"
echo "STUDIO FEATURES"
echo "============================================================================"
echo ""
echo "✓ Content Management - Create and edit posts, products, authors"
echo "✓ Vision Tool - Query content with GROQ"
echo "✓ Structure Tool - Organize content in a sidebar"
echo "✓ Live Preview - See content as it appears"
echo "✓ Real-time Sync - Changes sync to your Next.js app automatically"
echo ""
echo "============================================================================"
echo "TROUBLESHOOTING"
echo "============================================================================"
echo ""
echo "Port already in use?"
echo "  $ npm run dev -- --port 3334"
echo ""
echo "Authentication issues?"
echo "  $ sanity logout"
echo "  $ sanity login"
echo ""
echo "Build issues?"
echo "  $ rm -rf node_modules"
echo "  $ npm install"
echo "  $ npm run dev"
echo ""
